version: "3.2"

services:
  node:
    build:
      context: .
      dockerfile: docker/node/mysql/Dockerfile
    volumes:
      # https://stackoverflow.com/a/32785014/232619
      - .:/app
      - /app/node_modules
    command: /usr/local/wait-for-it.sh mongo:27017 -- npm start
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
      build: .
      ports:
        - "9092:9092"
      environment:
        KAFKA_ADVERTISED_HOST_NAME: localhost
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock